// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pabomyvzfjicpkeioncb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhYm9teXZ6ZmppY3BrZWlvbmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTMzNTEsImV4cCI6MjA3MDc2OTM1MX0.t8S-2AdK8CBE2kep1Z1OXx1oJxPcTVnNwjxqj9qNpQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});